    sources:
      - Azeret.glyphs
    axisOrder:
      - wght
      - ital
    familyName: Azeret Mono
    stat:
      AzeretMono[wght,ital].ttf:
      - name: Weight
        tag: wght
        values:
        - name: Thin
          value: 100
        - name: Light
          value: 300
        - name: Regular
          value: 400
          linkedValue: 700
          flags: 2
        - name: Medium
          value: 500
        - name: SemiBold
          value: 600
        - name: Bold
          value: 700
        - name: ExtraBold
          value: 800
        - name: Black
          value: 900
      - name: Italic
        tag: ital
        values:
        - name: Roman
          value: 0
          linkedValue: 12
          flags: 2
        - name: Italic
          value: 12